//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FENIX_KIOSCO.MCDIntegrationServices {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MCDIntegrationServices.wsModeloCanonicoDatosSoap")]
    public interface wsModeloCanonicoDatosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable CustomerAccount(string customerIdentification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetalleMovimiento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DetalleMovimiento(string customerIdentification, int accountConcept, System.DateTime movementInitialDate, System.DateTime movementFinalDate, string sUserQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetalleBloqueos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DetalleBloqueos(string customerIdentification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReporteHaberes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReporteHaberes(string customerIdentification, int accountId, string sUserQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExtractoGeneral", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ExtractoGeneral(string customerIdentification, int accountId, int movementMonth, int movementYear, string sUserQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeclaracionRenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DeclaracionRenta(string customerIdentification, int accountId, int movementMonth, int movementYear, string sUserQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarReporte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FENIX_KIOSCO.MCDIntegrationServices.ServiceResponse GenerarReporte(string sReporte, string customerIdentification, int accountId);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private byte[] reportField;
        
        private bool statusField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] Report {
            get {
                return this.reportField;
            }
            set {
                this.reportField = value;
                this.RaisePropertyChanged("Report");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsModeloCanonicoDatosSoapChannel : FENIX_KIOSCO.MCDIntegrationServices.wsModeloCanonicoDatosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsModeloCanonicoDatosSoapClient : System.ServiceModel.ClientBase<FENIX_KIOSCO.MCDIntegrationServices.wsModeloCanonicoDatosSoap>, FENIX_KIOSCO.MCDIntegrationServices.wsModeloCanonicoDatosSoap {
        
        public wsModeloCanonicoDatosSoapClient() {
        }
        
        public wsModeloCanonicoDatosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsModeloCanonicoDatosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsModeloCanonicoDatosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsModeloCanonicoDatosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable CustomerAccount(string customerIdentification) {
            return base.Channel.CustomerAccount(customerIdentification);
        }
        
        public System.Data.DataSet DetalleMovimiento(string customerIdentification, int accountConcept, System.DateTime movementInitialDate, System.DateTime movementFinalDate, string sUserQuery) {
            return base.Channel.DetalleMovimiento(customerIdentification, accountConcept, movementInitialDate, movementFinalDate, sUserQuery);
        }
        
        public System.Data.DataSet DetalleBloqueos(string customerIdentification) {
            return base.Channel.DetalleBloqueos(customerIdentification);
        }
        
        public System.Data.DataSet ReporteHaberes(string customerIdentification, int accountId, string sUserQuery) {
            return base.Channel.ReporteHaberes(customerIdentification, accountId, sUserQuery);
        }
        
        public System.Data.DataSet ExtractoGeneral(string customerIdentification, int accountId, int movementMonth, int movementYear, string sUserQuery) {
            return base.Channel.ExtractoGeneral(customerIdentification, accountId, movementMonth, movementYear, sUserQuery);
        }
        
        public System.Data.DataSet DeclaracionRenta(string customerIdentification, int accountId, int movementMonth, int movementYear, string sUserQuery) {
            return base.Channel.DeclaracionRenta(customerIdentification, accountId, movementMonth, movementYear, sUserQuery);
        }
        
        public FENIX_KIOSCO.MCDIntegrationServices.ServiceResponse GenerarReporte(string sReporte, string customerIdentification, int accountId) {
            return base.Channel.GenerarReporte(sReporte, customerIdentification, accountId);
        }
    }
}
