//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.1.
// 
#pragma warning disable 1591

namespace _Kiosko_WS.WebReferenceCIEL {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IISelectorbinding", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TSoapElemento))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TSoapTablero))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TSoapOcupacion))]
    public partial class IISelectorservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GeneraTurnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActivaTurnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminaTurnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevOcupacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevTurnosADespOperationCompleted;
        
        private System.Threading.SendOrPostCallback HellowordOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevElementosDigiturnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BroadcastMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevColasSelectorJornadaActualOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevLogoComoBytesOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevFechaHoraServidorOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevLineasTiqueteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImprimeTurnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevCodigoJornadaActualSalaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreaActivaEImprimeCitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelaCitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornaTurnoActualTerminalOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizaTransaccionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IISelectorservice() {
            this.Url = global::_Kiosko_WS.Properties.Settings.Default.Fenix_Kiosko_WS_WebReferenceCIEL_IISelectorservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GeneraTurnoCompletedEventHandler GeneraTurnoCompleted;
        
        /// <remarks/>
        public event ActivaTurnoCompletedEventHandler ActivaTurnoCompleted;
        
        /// <remarks/>
        public event EliminaTurnoCompletedEventHandler EliminaTurnoCompleted;
        
        /// <remarks/>
        public event DevOcupacionCompletedEventHandler DevOcupacionCompleted;
        
        /// <remarks/>
        public event DevTurnosADespCompletedEventHandler DevTurnosADespCompleted;
        
        /// <remarks/>
        public event HellowordCompletedEventHandler HellowordCompleted;
        
        /// <remarks/>
        public event DevElementosDigiturnoCompletedEventHandler DevElementosDigiturnoCompleted;
        
        /// <remarks/>
        public event BroadcastMsgCompletedEventHandler BroadcastMsgCompleted;
        
        /// <remarks/>
        public event DevColasSelectorJornadaActualCompletedEventHandler DevColasSelectorJornadaActualCompleted;
        
        /// <remarks/>
        public event DevLogoComoBytesCompletedEventHandler DevLogoComoBytesCompleted;
        
        /// <remarks/>
        public event DevFechaHoraServidorCompletedEventHandler DevFechaHoraServidorCompleted;
        
        /// <remarks/>
        public event DevLineasTiqueteCompletedEventHandler DevLineasTiqueteCompleted;
        
        /// <remarks/>
        public event ImprimeTurnoCompletedEventHandler ImprimeTurnoCompleted;
        
        /// <remarks/>
        public event DevCodigoJornadaActualSalaCompletedEventHandler DevCodigoJornadaActualSalaCompleted;
        
        /// <remarks/>
        public event CreaActivaEImprimeCitaCompletedEventHandler CreaActivaEImprimeCitaCompleted;
        
        /// <remarks/>
        public event CancelaCitaCompletedEventHandler CancelaCitaCompleted;
        
        /// <remarks/>
        public event RetornaTurnoActualTerminalCompletedEventHandler RetornaTurnoActualTerminalCompleted;
        
        /// <remarks/>
        public event ActualizaTransaccionCompletedEventHandler ActualizaTransaccionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#GeneraTurno", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public TSoapTURNO GeneraTurno(TSoapTURNO pSOAPTurno) {
            object[] results = this.Invoke("GeneraTurno", new object[] {
                        pSOAPTurno});
            return ((TSoapTURNO)(results[0]));
        }
        
        /// <remarks/>
        public void GeneraTurnoAsync(TSoapTURNO pSOAPTurno) {
            this.GeneraTurnoAsync(pSOAPTurno, null);
        }
        
        /// <remarks/>
        public void GeneraTurnoAsync(TSoapTURNO pSOAPTurno, object userState) {
            if ((this.GeneraTurnoOperationCompleted == null)) {
                this.GeneraTurnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneraTurnoOperationCompleted);
            }
            this.InvokeAsync("GeneraTurno", new object[] {
                        pSOAPTurno}, this.GeneraTurnoOperationCompleted, userState);
        }
        
        private void OnGeneraTurnoOperationCompleted(object arg) {
            if ((this.GeneraTurnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneraTurnoCompleted(this, new GeneraTurnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#ActivaTurno", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ActivaTurno(string uniCodigo, string strSala, string strUsuario) {
            object[] results = this.Invoke("ActivaTurno", new object[] {
                        uniCodigo,
                        strSala,
                        strUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActivaTurnoAsync(string uniCodigo, string strSala, string strUsuario) {
            this.ActivaTurnoAsync(uniCodigo, strSala, strUsuario, null);
        }
        
        /// <remarks/>
        public void ActivaTurnoAsync(string uniCodigo, string strSala, string strUsuario, object userState) {
            if ((this.ActivaTurnoOperationCompleted == null)) {
                this.ActivaTurnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivaTurnoOperationCompleted);
            }
            this.InvokeAsync("ActivaTurno", new object[] {
                        uniCodigo,
                        strSala,
                        strUsuario}, this.ActivaTurnoOperationCompleted, userState);
        }
        
        private void OnActivaTurnoOperationCompleted(object arg) {
            if ((this.ActivaTurnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivaTurnoCompleted(this, new ActivaTurnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#EliminaTurno", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string EliminaTurno(string uniCodigo, string strSala) {
            object[] results = this.Invoke("EliminaTurno", new object[] {
                        uniCodigo,
                        strSala});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EliminaTurnoAsync(string uniCodigo, string strSala) {
            this.EliminaTurnoAsync(uniCodigo, strSala, null);
        }
        
        /// <remarks/>
        public void EliminaTurnoAsync(string uniCodigo, string strSala, object userState) {
            if ((this.EliminaTurnoOperationCompleted == null)) {
                this.EliminaTurnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminaTurnoOperationCompleted);
            }
            this.InvokeAsync("EliminaTurno", new object[] {
                        uniCodigo,
                        strSala}, this.EliminaTurnoOperationCompleted, userState);
        }
        
        private void OnEliminaTurnoOperationCompleted(object arg) {
            if ((this.EliminaTurnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminaTurnoCompleted(this, new EliminaTurnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#DevOcupacion", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public TSoapOcupacion[] DevOcupacion() {
            object[] results = this.Invoke("DevOcupacion", new object[0]);
            return ((TSoapOcupacion[])(results[0]));
        }
        
        /// <remarks/>
        public void DevOcupacionAsync() {
            this.DevOcupacionAsync(null);
        }
        
        /// <remarks/>
        public void DevOcupacionAsync(object userState) {
            if ((this.DevOcupacionOperationCompleted == null)) {
                this.DevOcupacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevOcupacionOperationCompleted);
            }
            this.InvokeAsync("DevOcupacion", new object[0], this.DevOcupacionOperationCompleted, userState);
        }
        
        private void OnDevOcupacionOperationCompleted(object arg) {
            if ((this.DevOcupacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevOcupacionCompleted(this, new DevOcupacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#DevTurnosADesp", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public TSoapTableros DevTurnosADesp(string uniCodigo) {
            object[] results = this.Invoke("DevTurnosADesp", new object[] {
                        uniCodigo});
            return ((TSoapTableros)(results[0]));
        }
        
        /// <remarks/>
        public void DevTurnosADespAsync(string uniCodigo) {
            this.DevTurnosADespAsync(uniCodigo, null);
        }
        
        /// <remarks/>
        public void DevTurnosADespAsync(string uniCodigo, object userState) {
            if ((this.DevTurnosADespOperationCompleted == null)) {
                this.DevTurnosADespOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevTurnosADespOperationCompleted);
            }
            this.InvokeAsync("DevTurnosADesp", new object[] {
                        uniCodigo}, this.DevTurnosADespOperationCompleted, userState);
        }
        
        private void OnDevTurnosADespOperationCompleted(object arg) {
            if ((this.DevTurnosADespCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevTurnosADespCompleted(this, new DevTurnosADespCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#Helloword", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Helloword() {
            object[] results = this.Invoke("Helloword", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HellowordAsync() {
            this.HellowordAsync(null);
        }
        
        /// <remarks/>
        public void HellowordAsync(object userState) {
            if ((this.HellowordOperationCompleted == null)) {
                this.HellowordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHellowordOperationCompleted);
            }
            this.InvokeAsync("Helloword", new object[0], this.HellowordOperationCompleted, userState);
        }
        
        private void OnHellowordOperationCompleted(object arg) {
            if ((this.HellowordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HellowordCompleted(this, new HellowordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#DevElementosDigiturno", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public TSoapElementos DevElementosDigiturno(int intElemento) {
            object[] results = this.Invoke("DevElementosDigiturno", new object[] {
                        intElemento});
            return ((TSoapElementos)(results[0]));
        }
        
        /// <remarks/>
        public void DevElementosDigiturnoAsync(int intElemento) {
            this.DevElementosDigiturnoAsync(intElemento, null);
        }
        
        /// <remarks/>
        public void DevElementosDigiturnoAsync(int intElemento, object userState) {
            if ((this.DevElementosDigiturnoOperationCompleted == null)) {
                this.DevElementosDigiturnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevElementosDigiturnoOperationCompleted);
            }
            this.InvokeAsync("DevElementosDigiturno", new object[] {
                        intElemento}, this.DevElementosDigiturnoOperationCompleted, userState);
        }
        
        private void OnDevElementosDigiturnoOperationCompleted(object arg) {
            if ((this.DevElementosDigiturnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevElementosDigiturnoCompleted(this, new DevElementosDigiturnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#BroadcastMsg", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        public void BroadcastMsg(string MessageText, string MessagesServerDateTime) {
            this.Invoke("BroadcastMsg", new object[] {
                        MessageText,
                        MessagesServerDateTime});
        }
        
        /// <remarks/>
        public void BroadcastMsgAsync(string MessageText, string MessagesServerDateTime) {
            this.BroadcastMsgAsync(MessageText, MessagesServerDateTime, null);
        }
        
        /// <remarks/>
        public void BroadcastMsgAsync(string MessageText, string MessagesServerDateTime, object userState) {
            if ((this.BroadcastMsgOperationCompleted == null)) {
                this.BroadcastMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBroadcastMsgOperationCompleted);
            }
            this.InvokeAsync("BroadcastMsg", new object[] {
                        MessageText,
                        MessagesServerDateTime}, this.BroadcastMsgOperationCompleted, userState);
        }
        
        private void OnBroadcastMsgOperationCompleted(object arg) {
            if ((this.BroadcastMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BroadcastMsgCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#DevColasSelectorJornadaActual", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public TSoapElementos DevColasSelectorJornadaActual(string strSelector) {
            object[] results = this.Invoke("DevColasSelectorJornadaActual", new object[] {
                        strSelector});
            return ((TSoapElementos)(results[0]));
        }
        
        /// <remarks/>
        public void DevColasSelectorJornadaActualAsync(string strSelector) {
            this.DevColasSelectorJornadaActualAsync(strSelector, null);
        }
        
        /// <remarks/>
        public void DevColasSelectorJornadaActualAsync(string strSelector, object userState) {
            if ((this.DevColasSelectorJornadaActualOperationCompleted == null)) {
                this.DevColasSelectorJornadaActualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevColasSelectorJornadaActualOperationCompleted);
            }
            this.InvokeAsync("DevColasSelectorJornadaActual", new object[] {
                        strSelector}, this.DevColasSelectorJornadaActualOperationCompleted, userState);
        }
        
        private void OnDevColasSelectorJornadaActualOperationCompleted(object arg) {
            if ((this.DevColasSelectorJornadaActualCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevColasSelectorJornadaActualCompleted(this, new DevColasSelectorJornadaActualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#DevLogoComoBytes", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="base64Binary")]
        public byte[] DevLogoComoBytes(string strSelector) {
            object[] results = this.Invoke("DevLogoComoBytes", new object[] {
                        strSelector});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void DevLogoComoBytesAsync(string strSelector) {
            this.DevLogoComoBytesAsync(strSelector, null);
        }
        
        /// <remarks/>
        public void DevLogoComoBytesAsync(string strSelector, object userState) {
            if ((this.DevLogoComoBytesOperationCompleted == null)) {
                this.DevLogoComoBytesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevLogoComoBytesOperationCompleted);
            }
            this.InvokeAsync("DevLogoComoBytes", new object[] {
                        strSelector}, this.DevLogoComoBytesOperationCompleted, userState);
        }
        
        private void OnDevLogoComoBytesOperationCompleted(object arg) {
            if ((this.DevLogoComoBytesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevLogoComoBytesCompleted(this, new DevLogoComoBytesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#DevFechaHoraServidor", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string DevFechaHoraServidor() {
            object[] results = this.Invoke("DevFechaHoraServidor", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DevFechaHoraServidorAsync() {
            this.DevFechaHoraServidorAsync(null);
        }
        
        /// <remarks/>
        public void DevFechaHoraServidorAsync(object userState) {
            if ((this.DevFechaHoraServidorOperationCompleted == null)) {
                this.DevFechaHoraServidorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevFechaHoraServidorOperationCompleted);
            }
            this.InvokeAsync("DevFechaHoraServidor", new object[0], this.DevFechaHoraServidorOperationCompleted, userState);
        }
        
        private void OnDevFechaHoraServidorOperationCompleted(object arg) {
            if ((this.DevFechaHoraServidorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevFechaHoraServidorCompleted(this, new DevFechaHoraServidorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#DevLineasTiquete", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public TSoapLineasTiquete DevLineasTiquete(string strSelector) {
            object[] results = this.Invoke("DevLineasTiquete", new object[] {
                        strSelector});
            return ((TSoapLineasTiquete)(results[0]));
        }
        
        /// <remarks/>
        public void DevLineasTiqueteAsync(string strSelector) {
            this.DevLineasTiqueteAsync(strSelector, null);
        }
        
        /// <remarks/>
        public void DevLineasTiqueteAsync(string strSelector, object userState) {
            if ((this.DevLineasTiqueteOperationCompleted == null)) {
                this.DevLineasTiqueteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevLineasTiqueteOperationCompleted);
            }
            this.InvokeAsync("DevLineasTiquete", new object[] {
                        strSelector}, this.DevLineasTiqueteOperationCompleted, userState);
        }
        
        private void OnDevLineasTiqueteOperationCompleted(object arg) {
            if ((this.DevLineasTiqueteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevLineasTiqueteCompleted(this, new DevLineasTiqueteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#ImprimeTurno", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ImprimeTurno(string uniCodigo, string strSelector, string strNumeroTransaccion, string strAplicacionCliente, string strTurnoUsuario, string strUsuarioReceptor) {
            object[] results = this.Invoke("ImprimeTurno", new object[] {
                        uniCodigo,
                        strSelector,
                        strNumeroTransaccion,
                        strAplicacionCliente,
                        strTurnoUsuario,
                        strUsuarioReceptor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ImprimeTurnoAsync(string uniCodigo, string strSelector, string strNumeroTransaccion, string strAplicacionCliente, string strTurnoUsuario, string strUsuarioReceptor) {
            this.ImprimeTurnoAsync(uniCodigo, strSelector, strNumeroTransaccion, strAplicacionCliente, strTurnoUsuario, strUsuarioReceptor, null);
        }
        
        /// <remarks/>
        public void ImprimeTurnoAsync(string uniCodigo, string strSelector, string strNumeroTransaccion, string strAplicacionCliente, string strTurnoUsuario, string strUsuarioReceptor, object userState) {
            if ((this.ImprimeTurnoOperationCompleted == null)) {
                this.ImprimeTurnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImprimeTurnoOperationCompleted);
            }
            this.InvokeAsync("ImprimeTurno", new object[] {
                        uniCodigo,
                        strSelector,
                        strNumeroTransaccion,
                        strAplicacionCliente,
                        strTurnoUsuario,
                        strUsuarioReceptor}, this.ImprimeTurnoOperationCompleted, userState);
        }
        
        private void OnImprimeTurnoOperationCompleted(object arg) {
            if ((this.ImprimeTurnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImprimeTurnoCompleted(this, new ImprimeTurnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#DevCodigoJornadaActualSala", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string DevCodigoJornadaActualSala(string strCodigoSala) {
            object[] results = this.Invoke("DevCodigoJornadaActualSala", new object[] {
                        strCodigoSala});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DevCodigoJornadaActualSalaAsync(string strCodigoSala) {
            this.DevCodigoJornadaActualSalaAsync(strCodigoSala, null);
        }
        
        /// <remarks/>
        public void DevCodigoJornadaActualSalaAsync(string strCodigoSala, object userState) {
            if ((this.DevCodigoJornadaActualSalaOperationCompleted == null)) {
                this.DevCodigoJornadaActualSalaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevCodigoJornadaActualSalaOperationCompleted);
            }
            this.InvokeAsync("DevCodigoJornadaActualSala", new object[] {
                        strCodigoSala}, this.DevCodigoJornadaActualSalaOperationCompleted, userState);
        }
        
        private void OnDevCodigoJornadaActualSalaOperationCompleted(object arg) {
            if ((this.DevCodigoJornadaActualSalaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevCodigoJornadaActualSalaCompleted(this, new DevCodigoJornadaActualSalaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#CreaActivaEImprimeCita", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public TSoapTURNO CreaActivaEImprimeCita(TSoapTURNO pSOAPTurno, string strUsuario, string strSelector, string strNumeroTransaccion, string strAplicacionCliente, string strTurnoUsuario, string strUsuarioReceptor) {
            object[] results = this.Invoke("CreaActivaEImprimeCita", new object[] {
                        pSOAPTurno,
                        strUsuario,
                        strSelector,
                        strNumeroTransaccion,
                        strAplicacionCliente,
                        strTurnoUsuario,
                        strUsuarioReceptor});
            return ((TSoapTURNO)(results[0]));
        }
        
        /// <remarks/>
        public void CreaActivaEImprimeCitaAsync(TSoapTURNO pSOAPTurno, string strUsuario, string strSelector, string strNumeroTransaccion, string strAplicacionCliente, string strTurnoUsuario, string strUsuarioReceptor) {
            this.CreaActivaEImprimeCitaAsync(pSOAPTurno, strUsuario, strSelector, strNumeroTransaccion, strAplicacionCliente, strTurnoUsuario, strUsuarioReceptor, null);
        }
        
        /// <remarks/>
        public void CreaActivaEImprimeCitaAsync(TSoapTURNO pSOAPTurno, string strUsuario, string strSelector, string strNumeroTransaccion, string strAplicacionCliente, string strTurnoUsuario, string strUsuarioReceptor, object userState) {
            if ((this.CreaActivaEImprimeCitaOperationCompleted == null)) {
                this.CreaActivaEImprimeCitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreaActivaEImprimeCitaOperationCompleted);
            }
            this.InvokeAsync("CreaActivaEImprimeCita", new object[] {
                        pSOAPTurno,
                        strUsuario,
                        strSelector,
                        strNumeroTransaccion,
                        strAplicacionCliente,
                        strTurnoUsuario,
                        strUsuarioReceptor}, this.CreaActivaEImprimeCitaOperationCompleted, userState);
        }
        
        private void OnCreaActivaEImprimeCitaOperationCompleted(object arg) {
            if ((this.CreaActivaEImprimeCitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreaActivaEImprimeCitaCompleted(this, new CreaActivaEImprimeCitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#CancelaCita", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string CancelaCita(string strCodigo, string strCodigoUsuario, string strCodigoSala) {
            object[] results = this.Invoke("CancelaCita", new object[] {
                        strCodigo,
                        strCodigoUsuario,
                        strCodigoSala});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelaCitaAsync(string strCodigo, string strCodigoUsuario, string strCodigoSala) {
            this.CancelaCitaAsync(strCodigo, strCodigoUsuario, strCodigoSala, null);
        }
        
        /// <remarks/>
        public void CancelaCitaAsync(string strCodigo, string strCodigoUsuario, string strCodigoSala, object userState) {
            if ((this.CancelaCitaOperationCompleted == null)) {
                this.CancelaCitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelaCitaOperationCompleted);
            }
            this.InvokeAsync("CancelaCita", new object[] {
                        strCodigo,
                        strCodigoUsuario,
                        strCodigoSala}, this.CancelaCitaOperationCompleted, userState);
        }
        
        private void OnCancelaCitaOperationCompleted(object arg) {
            if ((this.CancelaCitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelaCitaCompleted(this, new CancelaCitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#RetornaTurnoActualTerminal", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string RetornaTurnoActualTerminal(string strCodigoTerminal) {
            object[] results = this.Invoke("RetornaTurnoActualTerminal", new object[] {
                        strCodigoTerminal});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RetornaTurnoActualTerminalAsync(string strCodigoTerminal) {
            this.RetornaTurnoActualTerminalAsync(strCodigoTerminal, null);
        }
        
        /// <remarks/>
        public void RetornaTurnoActualTerminalAsync(string strCodigoTerminal, object userState) {
            if ((this.RetornaTurnoActualTerminalOperationCompleted == null)) {
                this.RetornaTurnoActualTerminalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornaTurnoActualTerminalOperationCompleted);
            }
            this.InvokeAsync("RetornaTurnoActualTerminal", new object[] {
                        strCodigoTerminal}, this.RetornaTurnoActualTerminalOperationCompleted, userState);
        }
        
        private void OnRetornaTurnoActualTerminalOperationCompleted(object arg) {
            if ((this.RetornaTurnoActualTerminalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornaTurnoActualTerminalCompleted(this, new RetornaTurnoActualTerminalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ISelectorIntf-IISelector#ActualizaTransaccion", RequestNamespace="urn:ISelectorIntf-IISelector", ResponseNamespace="urn:ISelectorIntf-IISelector")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int ActualizaTransaccion(string strCodigoTerminal, string strCodigoTurno, string Cod_OrdenServicio, string Cli_DocId, string Cli_Nombre, string Cli_Telefono) {
            object[] results = this.Invoke("ActualizaTransaccion", new object[] {
                        strCodigoTerminal,
                        strCodigoTurno,
                        Cod_OrdenServicio,
                        Cli_DocId,
                        Cli_Nombre,
                        Cli_Telefono});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizaTransaccionAsync(string strCodigoTerminal, string strCodigoTurno, string Cod_OrdenServicio, string Cli_DocId, string Cli_Nombre, string Cli_Telefono) {
            this.ActualizaTransaccionAsync(strCodigoTerminal, strCodigoTurno, Cod_OrdenServicio, Cli_DocId, Cli_Nombre, Cli_Telefono, null);
        }
        
        /// <remarks/>
        public void ActualizaTransaccionAsync(string strCodigoTerminal, string strCodigoTurno, string Cod_OrdenServicio, string Cli_DocId, string Cli_Nombre, string Cli_Telefono, object userState) {
            if ((this.ActualizaTransaccionOperationCompleted == null)) {
                this.ActualizaTransaccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizaTransaccionOperationCompleted);
            }
            this.InvokeAsync("ActualizaTransaccion", new object[] {
                        strCodigoTerminal,
                        strCodigoTurno,
                        Cod_OrdenServicio,
                        Cli_DocId,
                        Cli_Nombre,
                        Cli_Telefono}, this.ActualizaTransaccionOperationCompleted, userState);
        }
        
        private void OnActualizaTransaccionOperationCompleted(object arg) {
            if ((this.ActualizaTransaccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizaTransaccionCompleted(this, new ActualizaTransaccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:UsoapTURNO")]
    public partial class TSoapTURNO {
        
        private string uNIGUIDField;
        
        private string uNITURNOField;
        
        private bool iMPRIMIRField;
        
        private string hORASOLICITUDField;
        
        private string sALAField;
        
        private string uSUARIOEMISORField;
        
        private string hARDWARERECEPTORField;
        
        private string oBSERVACIONESField;
        
        private string sELECTORField;
        
        private string cOLAField;
        
        private string tURNOField;
        
        private string cLIENTEField;
        
        private string iDCLIENTEField;
        
        private string nOMBREField;
        
        private string pRIORIDADField;
        
        private string tIPOIDField;
        
        private string eRRORField;
        
        private string mODOField;
        
        private string aREAField;
        
        private string tIPOCLIENTEField;
        
        private string sERVICIOField;
        
        private string sUBSERVICIOField;
        
        private string uSUARIORECEPTORField;
        
        private string tURNOUSUARIOField;
        
        /// <comentarios/>
        public string UNIGUID {
            get {
                return this.uNIGUIDField;
            }
            set {
                this.uNIGUIDField = value;
            }
        }
        
        /// <comentarios/>
        public string UNITURNO {
            get {
                return this.uNITURNOField;
            }
            set {
                this.uNITURNOField = value;
            }
        }
        
        /// <comentarios/>
        public bool IMPRIMIR {
            get {
                return this.iMPRIMIRField;
            }
            set {
                this.iMPRIMIRField = value;
            }
        }
        
        /// <comentarios/>
        public string HORASOLICITUD {
            get {
                return this.hORASOLICITUDField;
            }
            set {
                this.hORASOLICITUDField = value;
            }
        }
        
        /// <comentarios/>
        public string SALA {
            get {
                return this.sALAField;
            }
            set {
                this.sALAField = value;
            }
        }
        
        /// <comentarios/>
        public string USUARIOEMISOR {
            get {
                return this.uSUARIOEMISORField;
            }
            set {
                this.uSUARIOEMISORField = value;
            }
        }
        
        /// <comentarios/>
        public string HARDWARERECEPTOR {
            get {
                return this.hARDWARERECEPTORField;
            }
            set {
                this.hARDWARERECEPTORField = value;
            }
        }
        
        /// <comentarios/>
        public string OBSERVACIONES {
            get {
                return this.oBSERVACIONESField;
            }
            set {
                this.oBSERVACIONESField = value;
            }
        }
        
        /// <comentarios/>
        public string SELECTOR {
            get {
                return this.sELECTORField;
            }
            set {
                this.sELECTORField = value;
            }
        }
        
        /// <comentarios/>
        public string COLA {
            get {
                return this.cOLAField;
            }
            set {
                this.cOLAField = value;
            }
        }
        
        /// <comentarios/>
        public string TURNO {
            get {
                return this.tURNOField;
            }
            set {
                this.tURNOField = value;
            }
        }
        
        /// <comentarios/>
        public string CLIENTE {
            get {
                return this.cLIENTEField;
            }
            set {
                this.cLIENTEField = value;
            }
        }
        
        /// <comentarios/>
        public string IDCLIENTE {
            get {
                return this.iDCLIENTEField;
            }
            set {
                this.iDCLIENTEField = value;
            }
        }
        
        /// <comentarios/>
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
            }
        }
        
        /// <comentarios/>
        public string PRIORIDAD {
            get {
                return this.pRIORIDADField;
            }
            set {
                this.pRIORIDADField = value;
            }
        }
        
        /// <comentarios/>
        public string TIPOID {
            get {
                return this.tIPOIDField;
            }
            set {
                this.tIPOIDField = value;
            }
        }
        
        /// <comentarios/>
        public string ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
            }
        }
        
        /// <comentarios/>
        public string MODO {
            get {
                return this.mODOField;
            }
            set {
                this.mODOField = value;
            }
        }
        
        /// <comentarios/>
        public string AREA {
            get {
                return this.aREAField;
            }
            set {
                this.aREAField = value;
            }
        }
        
        /// <comentarios/>
        public string TIPOCLIENTE {
            get {
                return this.tIPOCLIENTEField;
            }
            set {
                this.tIPOCLIENTEField = value;
            }
        }
        
        /// <comentarios/>
        public string SERVICIO {
            get {
                return this.sERVICIOField;
            }
            set {
                this.sERVICIOField = value;
            }
        }
        
        /// <comentarios/>
        public string SUBSERVICIO {
            get {
                return this.sUBSERVICIOField;
            }
            set {
                this.sUBSERVICIOField = value;
            }
        }
        
        /// <comentarios/>
        public string USUARIORECEPTOR {
            get {
                return this.uSUARIORECEPTORField;
            }
            set {
                this.uSUARIORECEPTORField = value;
            }
        }
        
        /// <comentarios/>
        public string TURNOUSUARIO {
            get {
                return this.tURNOUSUARIOField;
            }
            set {
                this.tURNOUSUARIOField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:USoapLineasTiquete")]
    public partial class TSoapLineasTiquete {
        
        private bool fuenteDobleLinea4Field;
        
        private bool fuenteDobleLinea5Field;
        
        private bool fuenteDobleLinea6Field;
        
        private bool imprimirLinea5Field;
        
        private bool imprimirLinea6Field;
        
        private string linea1Field;
        
        private string linea2Field;
        
        private string linea3Field;
        
        private string linea4Field;
        
        private string linea5Field;
        
        private string linea6Field;
        
        /// <comentarios/>
        public bool FuenteDobleLinea4 {
            get {
                return this.fuenteDobleLinea4Field;
            }
            set {
                this.fuenteDobleLinea4Field = value;
            }
        }
        
        /// <comentarios/>
        public bool FuenteDobleLinea5 {
            get {
                return this.fuenteDobleLinea5Field;
            }
            set {
                this.fuenteDobleLinea5Field = value;
            }
        }
        
        /// <comentarios/>
        public bool FuenteDobleLinea6 {
            get {
                return this.fuenteDobleLinea6Field;
            }
            set {
                this.fuenteDobleLinea6Field = value;
            }
        }
        
        /// <comentarios/>
        public bool ImprimirLinea5 {
            get {
                return this.imprimirLinea5Field;
            }
            set {
                this.imprimirLinea5Field = value;
            }
        }
        
        /// <comentarios/>
        public bool ImprimirLinea6 {
            get {
                return this.imprimirLinea6Field;
            }
            set {
                this.imprimirLinea6Field = value;
            }
        }
        
        /// <comentarios/>
        public string Linea1 {
            get {
                return this.linea1Field;
            }
            set {
                this.linea1Field = value;
            }
        }
        
        /// <comentarios/>
        public string Linea2 {
            get {
                return this.linea2Field;
            }
            set {
                this.linea2Field = value;
            }
        }
        
        /// <comentarios/>
        public string Linea3 {
            get {
                return this.linea3Field;
            }
            set {
                this.linea3Field = value;
            }
        }
        
        /// <comentarios/>
        public string Linea4 {
            get {
                return this.linea4Field;
            }
            set {
                this.linea4Field = value;
            }
        }
        
        /// <comentarios/>
        public string Linea5 {
            get {
                return this.linea5Field;
            }
            set {
                this.linea5Field = value;
            }
        }
        
        /// <comentarios/>
        public string Linea6 {
            get {
                return this.linea6Field;
            }
            set {
                this.linea6Field = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:USoapElemento")]
    public partial class TSoapElemento {
        
        private string cODIGOField;
        
        private string nOMBREField;
        
        private string tIPOELEMENTOField;
        
        private string cOD_SALAField;
        
        private string nOMBRE_SALAField;
        
        private string cOD_OFICINAField;
        
        private string nOMBRE_OFICINAField;
        
        /// <comentarios/>
        public string CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
            }
        }
        
        /// <comentarios/>
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
            }
        }
        
        /// <comentarios/>
        public string TIPOELEMENTO {
            get {
                return this.tIPOELEMENTOField;
            }
            set {
                this.tIPOELEMENTOField = value;
            }
        }
        
        /// <comentarios/>
        public string COD_SALA {
            get {
                return this.cOD_SALAField;
            }
            set {
                this.cOD_SALAField = value;
            }
        }
        
        /// <comentarios/>
        public string NOMBRE_SALA {
            get {
                return this.nOMBRE_SALAField;
            }
            set {
                this.nOMBRE_SALAField = value;
            }
        }
        
        /// <comentarios/>
        public string COD_OFICINA {
            get {
                return this.cOD_OFICINAField;
            }
            set {
                this.cOD_OFICINAField = value;
            }
        }
        
        /// <comentarios/>
        public string NOMBRE_OFICINA {
            get {
                return this.nOMBRE_OFICINAField;
            }
            set {
                this.nOMBRE_OFICINAField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:USoapElemento")]
    public partial class TSoapElementos {
        
        private TSoapElemento[] soapArrayField;
        
        /// <comentarios/>
        public TSoapElemento[] SoapArray {
            get {
                return this.soapArrayField;
            }
            set {
                this.soapArrayField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:USoapTablero")]
    public partial class TSoapTablero {
        
        private string tURNOField;
        
        private string cODCLIENTEField;
        
        private string iDCLIENTEField;
        
        private string nOMBREField;
        
        private string tIPOIDField;
        
        private string sALAField;
        
        private string hARDWARERECEPTORField;
        
        private string cOLAField;
        
        private string hORASOLICITUDField;
        
        private string hORALLAMADOField;
        
        /// <comentarios/>
        public string TURNO {
            get {
                return this.tURNOField;
            }
            set {
                this.tURNOField = value;
            }
        }
        
        /// <comentarios/>
        public string CODCLIENTE {
            get {
                return this.cODCLIENTEField;
            }
            set {
                this.cODCLIENTEField = value;
            }
        }
        
        /// <comentarios/>
        public string IDCLIENTE {
            get {
                return this.iDCLIENTEField;
            }
            set {
                this.iDCLIENTEField = value;
            }
        }
        
        /// <comentarios/>
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
            }
        }
        
        /// <comentarios/>
        public string TIPOID {
            get {
                return this.tIPOIDField;
            }
            set {
                this.tIPOIDField = value;
            }
        }
        
        /// <comentarios/>
        public string SALA {
            get {
                return this.sALAField;
            }
            set {
                this.sALAField = value;
            }
        }
        
        /// <comentarios/>
        public string HARDWARERECEPTOR {
            get {
                return this.hARDWARERECEPTORField;
            }
            set {
                this.hARDWARERECEPTORField = value;
            }
        }
        
        /// <comentarios/>
        public string COLA {
            get {
                return this.cOLAField;
            }
            set {
                this.cOLAField = value;
            }
        }
        
        /// <comentarios/>
        public string HORASOLICITUD {
            get {
                return this.hORASOLICITUDField;
            }
            set {
                this.hORASOLICITUDField = value;
            }
        }
        
        /// <comentarios/>
        public string HORALLAMADO {
            get {
                return this.hORALLAMADOField;
            }
            set {
                this.hORALLAMADOField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:USoapTablero")]
    public partial class TSoapTableros {
        
        private TSoapTablero[] soapArrayField;
        
        private int sECONDSField;
        
        private string eRRORField;
        
        /// <comentarios/>
        public TSoapTablero[] SoapArray {
            get {
                return this.soapArrayField;
            }
            set {
                this.soapArrayField = value;
            }
        }
        
        /// <comentarios/>
        public int SECONDS {
            get {
                return this.sECONDSField;
            }
            set {
                this.sECONDSField = value;
            }
        }
        
        /// <comentarios/>
        public string ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:USoapOcupacion")]
    public partial class TSoapOcupacion {
        
        private string sALAField;
        
        private int oCUPACIONField;
        
        /// <comentarios/>
        public string SALA {
            get {
                return this.sALAField;
            }
            set {
                this.sALAField = value;
            }
        }
        
        /// <comentarios/>
        public int OCUPACION {
            get {
                return this.oCUPACIONField;
            }
            set {
                this.oCUPACIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GeneraTurnoCompletedEventHandler(object sender, GeneraTurnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeneraTurnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeneraTurnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TSoapTURNO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TSoapTURNO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ActivaTurnoCompletedEventHandler(object sender, ActivaTurnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActivaTurnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActivaTurnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EliminaTurnoCompletedEventHandler(object sender, EliminaTurnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminaTurnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminaTurnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DevOcupacionCompletedEventHandler(object sender, DevOcupacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevOcupacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevOcupacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TSoapOcupacion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TSoapOcupacion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DevTurnosADespCompletedEventHandler(object sender, DevTurnosADespCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevTurnosADespCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevTurnosADespCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TSoapTableros Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TSoapTableros)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HellowordCompletedEventHandler(object sender, HellowordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HellowordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HellowordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DevElementosDigiturnoCompletedEventHandler(object sender, DevElementosDigiturnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevElementosDigiturnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevElementosDigiturnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TSoapElementos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TSoapElementos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BroadcastMsgCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DevColasSelectorJornadaActualCompletedEventHandler(object sender, DevColasSelectorJornadaActualCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevColasSelectorJornadaActualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevColasSelectorJornadaActualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TSoapElementos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TSoapElementos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DevLogoComoBytesCompletedEventHandler(object sender, DevLogoComoBytesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevLogoComoBytesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevLogoComoBytesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DevFechaHoraServidorCompletedEventHandler(object sender, DevFechaHoraServidorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevFechaHoraServidorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevFechaHoraServidorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DevLineasTiqueteCompletedEventHandler(object sender, DevLineasTiqueteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevLineasTiqueteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevLineasTiqueteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TSoapLineasTiquete Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TSoapLineasTiquete)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ImprimeTurnoCompletedEventHandler(object sender, ImprimeTurnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImprimeTurnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImprimeTurnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DevCodigoJornadaActualSalaCompletedEventHandler(object sender, DevCodigoJornadaActualSalaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevCodigoJornadaActualSalaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevCodigoJornadaActualSalaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreaActivaEImprimeCitaCompletedEventHandler(object sender, CreaActivaEImprimeCitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreaActivaEImprimeCitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreaActivaEImprimeCitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TSoapTURNO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TSoapTURNO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CancelaCitaCompletedEventHandler(object sender, CancelaCitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelaCitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelaCitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RetornaTurnoActualTerminalCompletedEventHandler(object sender, RetornaTurnoActualTerminalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornaTurnoActualTerminalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornaTurnoActualTerminalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ActualizaTransaccionCompletedEventHandler(object sender, ActualizaTransaccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizaTransaccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizaTransaccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591